---
- name: install backend first node 
  hosts: test
  gather_facts: no
  remote_user: root
  roles: 
#    - { role: init_repo}
#    - { role: chrony } 
    - { role: test_ansible_command}
#    - { role: memcached}
#    - { role: percona_xtra_db_cluster}
#    - { role: keepalived }
#    - { role: haproxy }
#    - { role: docker }

#- name: install backend backup node 
#  hosts: bk-#controller
#    - { role: neutron-server }

# name: install controller backup node 
# hosts: bk-controller
# remote_user: root
# roles: 
#    - { role: keystone }
#    - { role: glance } 
#    - { role: nova-api }
#    - { role: neutron-server }
#    - { role: horizon } 
#    - { role: cinder-api }
#    - { role: cinder-volume }
#    - { role: swift_proxy }
