---
# Password RabbitMQ User
SSH_USER: root
SQL_ROOT_PASSWD: Vttek@123
RB_OPENSTACK: Y2g8AiB6DjwpvQRKqdU7mXcolwPHNQUT

# Password Openstack User
ops_user_demo: demo
OPS_DEMO_PASS: GfvDCTgUVLYsotdmjCiK6tIRATsgjSTp
ops_user_glance: glance
OPS_GLANCE_PASS: JBNpfryKwey6kcsditbd77LptDWEiZfD
ops_user_cinder: cinder 
OPS_CINDER_PASS: tdy0llhzHk2DnQbQcuXZ5KV4EUobdY3o
ops_user_nova: nova 
OPS_NOVA_PASS: CVVW5ThnUFuAXFCF3OLk1gj6atg9NB5m
ops_user_placement: placement 
OPS_PLACEMENT_PASS: sQWRKWbkbB3RcmMT4aXe2lntXOIubGvj
ops_user_swift: swift 
OPS_SWIFT_PASS: MqWRKWbkbB3RcmMT4aXe2lntXOIubGvJ
ops_user_neutron: neutron
OPS_NEUTRON_PASS: ATqCSRFyZs28lOUHdAmzSxtSN7jht2bL
METADATA_SECRET: I8IZc2GMAYbTfkgi8R7xqw3RSoxfwZ0S

# Password Database User
db_glance_name: glance
db_user_glance: glance 
DB_GLANCE_PASS: kFUVAMyZgUgcD8lSG9aA8kH2HPmo7fP0
db_cinder_name: cinder 
db_user_cinder: cinder 
DB_CINDER_PASS: 4EOFRtdnyvflTmI4OFEkllULddfdor0w
db_keystone_name: keystone
db_user_keystone: keystone 
DB_KEYSTONE_PASS: iVVWSMqdfXfuDGuzKIk7u1OwSXoeTokI
db_nova_name: nova 
db_nova_api_name: nova_api
db_user_nova: nova  
DB_NOVA_PASS: tDYYivjrHo749yokhU7utc2GLlJezi14
db_neutron_name: neutron
db_user_neutron: neutron
DB_NEUTRON_PASS: CiH7J2U88DhWNECBYQH7A5Okyu3F4uRe

#Password Ceph User
NOVA_RBD_USER: volumes
NOVA_RBD_SECRET_UUID: d2ddabda-ff6a-451d-b8be-4edd3172e702
#SWIFT
HASH_PATH_SUFFIX: UWXY~uwxy
HASH_PATH_PERFIX: jkml~JKML
client_images_key: AQC9V1Fcm46bARAAnxC/q2D9Y0YJWNXULm/cjQ==
nova_images_type: rbd 
nova_images_rbd_pool: vms 
nova_images_rbd_ceph_conf: /etc/ceph/ceph.conf 
nova_rbd_user: volumes
nova_rbd_secret_uuid: d2ddabda-ff6a-451d-b8be-4edd3172e702

