---
- name: POST BEFORE "{{ inventory_hostname }}" and {{ task_index }}  and {{ service_name }}
  uri:
    url: http://{{software_deployment_host}}:4321/api/v1/tasks/update_task
    method: POST
    body_format: json
    body: {"node_ip":"{{ inventory_hostname }}","task_index":"{{ task_index }}", "service_name":"{{ service_name }}","state":"before_task" }
    return_content: yes

