\cp init_repo/tasks/main.yml backup/tasks/main.yml
\cp init_repo/tasks/main.yml ceph/tasks/main.yml
\cp init_repo/tasks/main.yml chrony/tasks/main.yml
\cp init_repo/tasks/main.yml cinder-api/tasks/main.yml
\cp init_repo/tasks/main.yml cinder-volume/tasks/main.yml
\cp init_repo/tasks/main.yml docker/tasks/main.yml
\cp init_repo/tasks/main.yml elasticsearch/tasks/main.yml
\cp init_repo/tasks/main.yml fluentd/tasks/main.yml
\cp init_repo/tasks/main.yml glance-api/tasks/main.yml
\cp init_repo/tasks/main.yml haproxy/tasks/main.yml
\cp init_repo/tasks/main.yml horizon/tasks/main.yml
\cp init_repo/tasks/main.yml init_repo/tasks/main.yml
\cp init_repo/tasks/main.yml keepalived/tasks/main.yml
\cp init_repo/tasks/main.yml keystone/tasks/main.yml
\cp init_repo/tasks/main.yml kibana/tasks/main.yml
\cp init_repo/tasks/main.yml memcached/tasks/main.yml
\cp init_repo/tasks/main.yml neutron-dhcp_agent/tasks/main.yml
\cp init_repo/tasks/main.yml neutron-metadata_agent/tasks/main.yml
\cp init_repo/tasks/main.yml neutron-openvswitch_agent/tasks/main.yml
\cp init_repo/tasks/main.yml neutron-server/tasks/main.yml
\cp init_repo/tasks/main.yml neutron-sriov_agent/tasks/main.yml
\cp init_repo/tasks/main.yml nova-api/tasks/main.yml
\cp init_repo/tasks/main.yml nova-compute/tasks/main.yml
\cp init_repo/tasks/main.yml openday_light/tasks/main.yml
\cp init_repo/tasks/main.yml openvswitch_dpdk/tasks/main.yml
\cp init_repo/tasks/main.yml percona_xtra_db_cluster/tasks/main.yml
\cp init_repo/tasks/main.yml prometheus/tasks/main.yml
\cp init_repo/tasks/main.yml qemu/tasks/main.yml
\cp init_repo/tasks/main.yml rabbitmq/tasks/main.yml
\cp init_repo/tasks/main.yml swift_proxy/tasks/main.yml
\cp init_repo/tasks/main.yml test_ansible_command/tasks/main.yml
