- block:
  - name: 1.cp selinux.conf.j2 /etc/selinux/config
    debug: msg='Starting 1-------------------------------------------->'
  - include: extends/before.yml task_index=1
  - template:
      src: selinux.conf.j2
      dest: /etc/selinux/config
      owner: root
      group: root
      mode: '0644'
      backup: yes
    register: infos
  - include: extends/after_ok.yml task_index=1 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=1 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '1'
- block:
  - name: 2.stop selinux
    debug: msg='Starting 2-------------------------------------------->'
  - include: extends/before.yml task_index=2
  - command: '{{ item }}'
    with_items:
    - sudo setenforce 0
    register: infos
    ignore_errors: yes
  - include: extends/after_ok.yml task_index=2 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=2 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '2'
- block:
  - name: 3.systemctl stop iptables
    debug: msg='Starting 3-------------------------------------------->'
  - include: extends/before.yml task_index=3
  - systemd:
      name: iptables
      enabled: no
      masked: no
    register: infos
    ignore_errors: yes
  - include: extends/after_ok.yml task_index=3 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=3 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '3'
- block:
  - name: 4.systemctl stop firewalld
    debug: msg='Starting 4-------------------------------------------->'
  - include: extends/before.yml task_index=4
  - systemd:
      name: firewalld
      enabled: no
      masked: no
    register: infos
    ignore_errors: yes
  - include: extends/after_ok.yml task_index=4 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=4 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '4'
- block:
  - name: 5.test_ansible_command
    debug: msg='Starting 5-------------------------------------------->'
  - include: extends/before.yml task_index=5
  - command: '{{ item }}'
    with_items:
    - echo "{{ inventory_hostname }}"
    - touch /home/"{{ service_name }}"
    - echo "{{ group_name }}"  > /home/"{{ service_name }}"

#    - cp /home/lamtv10/lkt /home/lamtv10/

    register: infos
  - include: extends/after_ok.yml task_index=5 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=5 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '5'
- block:
  - name: 6.cp local.repo.j2 /etc/yum.repos.d/local.repo
    debug: msg='Starting 6-------------------------------------------->'
  - include: extends/before.yml task_index=6
  - template:
      src: local.repo.j2
      dest: /etc/yum.repos.d/local.repo
      owner: root
      group: root
      mode: '0644'
      backup: yes
    register: infos
  - include: extends/after_ok.yml task_index=6 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=6 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '6'
- block:
  - name: 7.cp docker.repo.j2 /etc/yum.repos.d/docker.repo
    debug: msg='Starting 7-------------------------------------------->'
  - include: extends/before.yml task_index=7
  - template:
      src: docker.repo.j2
      dest: /etc/yum.repos.d/docker.repo
      owner: root
      group: root
      mode: '0644'
      backup: yes
    register: infos
  - include: extends/after_ok.yml task_index=7 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=7 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '7'

- block:
  - name: 8.example GET
    debug: msg='Starting 8-------------------------------------------->'
  - include: extends/before.yml task_index=8
  - uri:
      url: http://{{ repository }}:8774
      method: GET
      body_format: json
      return_content: yes
    register: infos
  - include: extends/after_ok.yml task_index=8 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=8 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '8'