- name: demo2 task1
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task1" > /home/lamtv10/file1.txt
  ignore_errors: yes


- name: demo2 task2
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task2" > /home/lamtv10/file2.txt
  ignore_errors: yes


- name: demo2 task3
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task3" > /home/lamtv10/file3.txt
  ignore_errors: yes


- name: demo2 task4
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task4" > /home/lamtv10/file4.txt
  ignore_errors: yes


- name: demo2 task5
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task5" > /home/lamtv10/file5.txt
  ignore_errors: yes


- name: demo2 task6
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task6" > /home/lamtv10/file6.txt
  ignore_errors: yes


- name: demo2 task7
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task7" > /home/lamtv10/file7.txt
  ignore_errors: yes


- name: demo2 task8
  shell: '{{ item }}'
  with_items:
  - mkdir -p /home/lamtv10
  - echo "demo2 task8" > /home/lamtv10/file8.txt
  ignore_errors: yes
