---
service_name: haproxy
Haproxy_Config:
  - service_name: horizon
    port: 80 
    balance: "source"  
    option: "http-request del-header X-Forwarded-Proto" 
    config: "check inter 2000 rise 2 fall 5"

  - service_name: neutron_server
    port: 9696
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto" 
    config: "check inter 2000 rise 2 fall 5"

  - service_name: cinder_api
    port: 8776
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto" 
    config: "check inter 2000 rise 2 fall 5"

  - service_name: keystone
    port: 5000
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto"
    config: "check inter 2000 rise 2 fall 5"
  
  - service_name: nova_novncproxy
    port: 6080
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto" 
    config: "check inter 2000 rise 2 fall 5"
  
  - service_name: nova_api
    port: 8774
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto" 
    config: "check inter 2000 rise 2 fall 5"

  - service_name: nova_placement_api
    port: 8778
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto"
    config: "check inter 2000 rise 2 fall 5" 

  - service_name: nova_metadata
    port: 8775
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto"
    config: "check inter 2000 rise 2 fall 5" 

  - service_name: glance_api
    port: 9292
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto" 
    config: "check inter 2000 rise 2 fall 5"

  - service_name: glance_registry
    port: 9191
    balance: "roundrobin"
    option: "http-request del-header X-Forwarded-Proto"
    config: "check inter 2000 rise 2 fall 5" 

